[package]
name = "egui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.0"
egui = "0.33.0"
egui_tabs = "0.2.1"
egui_dock = "0.18.0"
rfd = "0.15.4"
image = "0.25.8"
nalgebra = "0.34.1"